---
title: "R Notebook"
output: html_notebook
---

Code Attribution:
Incomplete Data Analysis Workshop1 solutions -

<https://learn-eu-central-1-prod-fleet01-xythos.s3.eu-central-1.amazonaws.com/5d1b15b77a8ac/8552382?response-cache-control=private%2C%20max-age%3D21600&response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27solutions_workshop_1.pdf&response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20201025T120000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=AKIAZH6WM4PL5M5HI5WH%2F20201025%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Signature=c9581a6ab6ebd2612e42cf7c5f00b0071f07d483da1c2146170b4cce168abaa8>

Incomplete Data Analysis Workshop 2 solutions - 
<https://learn-eu-central-1-prod-fleet01-xythos.s3.eu-central-1.amazonaws.com/5d1b15b77a8ac/9025404?response-cache-control=private%2C%20max-age%3D21600&response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27solutions_workshop_2.pdf&response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20201025T180000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=AKIAZH6WM4PL5M5HI5WH%2F20201025%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Signature=723096adbbeefa8485c25fd13549866b74874e89fcb1ed5a60b1b7555416e13c>

Incomplete Data Analysis Week 3 Single_Imputation_Example -
<https://www.learn.ed.ac.uk/bbcswebdav/pid-5372532-dt-content-rid-16227115_1/xid-16227115_1>

Quick-R by Data Camp - 
<https://www.statmethods.net/stats/correlations.html>

Question 3a


```{r}

set.seed(1)

#First define the variables, where rnorm(n) draws n random variables under a normal distribution, with default mean = 0 and sd = 1

n = 500

Z1 = rnorm(n)
Z2 = rnorm(n)
Z3 = rnorm(n)

Y1 = 1 + Z1
Y2 = 5 + (2 * Z1) + Z2


a = 2
b = 0

missingMCAR = a * (Y1 - 1) + b  * (Y2 - 5) + Z3 <0

#ind_missing creates an index of TRUE or FALSE values depending on wether or not a value in the set missing is < Z1

ind_missing = which(missingMCAR == TRUE)

#Then y2_obs and y_mis uses the index to decide which values are missing in our currently fully observed set of Y2

Y2_obs = Y2[-ind_missing]
Y2_mis = Y2[ind_missing]

#Then we show a density plot of Y2 and Y2 without missing values (Y_obs), code heavily borrowed from workshop 1 solutions, url at top of document.

plot(density(Y2), lwd = 2, col = "blue", xlab =expression(Y[2]),
     main = "Y2", ylim =c(0, 0.3))
lines(density(Y2_obs), lwd = 2, col = "red")

legend(8, 0.25, legend =c("Complete data", "Observed data"),col =c("blue", "red"), lty =c(1,1), lwd =c(2,2), bty ="n")

```


Question 3b


```{r}
set.seed(1)

#First find a linear regression model using R's lm function

fit = lm(Y2_obs ~ Y1[-ind_missing])


#Add random noise

pred_reg_Y2 = predict(fit, newdata = list(Y2)) + rnorm(n, 0,summary(fit)$sigma)

#Replace missing values with stochastic regression model data

reg_Y2 = ifelse((missing) == TRUE, pred_reg_Y2, Y2)

#And plot


plot(density(Y2), lwd = 2, col = "blue", xlab =expression(Y[2]),
     main = "Y2", ylim =c(0, 0.3))
lines(density(reg_Y2), lwd = 2, col = "green")

legend(8, 0.25, legend =c("Complete data", "Regression Input"),col =c("blue", "green"), lty =c(1,1), lwd =c(2,2), bty ="n")


#A comprarison graph between Q3a and Q3b

plot(density(Y2), lwd = 2, col = "blue", xlab =expression(Y[2]),
     main = "Y2", ylim =c(0, 0.3))
lines(density(reg_Y2), lwd = 2, col = "green")
lines(density(Y2_obs), lwd = 2, col = "red")

legend(8, 0.25, legend =c("Complete data", "Regression Input","Observed Data"),col =c("blue", "green", "red"), lty =c(1,1,1), lwd =c(2,2,2), bty ="n")

```


Question 3 c


```{r}
set.seed(1)

#It's not necessary to fully copy the code from 3a but I have done anyway, just altering the values of a & b, just in case the code is run independently of 3a.

#For more comments on the code see Q3a

n = 500

Z1 = rnorm(n)
Z2 = rnorm(n)
Z3 = rnorm(n)

Y1 = 1 + Z1
Y2 = 5 + (2 * Z1) + Z2


a = 0
b = 2


missingMNAR = a * (Y1 - 1) + b  * (Y2 - 5) + Z3 <0


ind_missingMNAR = which(missingMNAR == TRUE)


Y2_obs_MNAR = Y2[-ind_missingMNAR]
Y2_mis_MNAR = Y2[ind_missingMNAR]


plot(density(Y2), lwd = 2, col = "blue", xlab =expression(Y[2]),
     main = "Y2", ylim =c(0, 0.3))
lines(density(Y2_obs_MNAR), lwd = 2, col = "red")

legend(8, 0.25, legend =c("Complete data", "Observed data"),col =c("blue", "red"), lty =c(1,1), lwd =c(2,2), bty ="n")


#A small line to see how much data is missing
length(Y2_mis_MNAR)

```


Question 3d

```{r}
set.seed(1)

#First find a linear regression model using R's lm function

fitMNAR = lm(Y2_obs_MNAR ~ Y1[-ind_missingMNAR])


#Add random noise

pred_reg_Y2_MNAR = predict(fitMNAR, newdata = list(Y2)) + rnorm(n, 0,summary(fit)$sigma)

#Replace missing values with stochastic regression model data

reg_Y2_MNAR = ifelse((missingMNAR) == TRUE, pred_reg_Y2_MNAR, Y2)

#And plot


plot(density(Y2), lwd = 2, col = "blue", xlab =expression(Y[2]),
     main = "Y2 with MNAR", ylim =c(0, 0.3))
lines(density(reg_Y2_MNAR), lwd = 2, col = "green")

legend(8, 0.25, legend =c("Complete data", "MNAR Regression Input"),col =c("blue", "green"), lty =c(1,1), lwd =c(2,2), bty ="n")


#A comprarison graph between Q3a and Q3b

plot(density(Y2), lwd = 2, col = "blue", xlab =expression(Y[2]),
     main = "Y2", ylim =c(0, 0.3))
lines(density(reg_Y2_MNAR), lwd = 2, col = "green")
lines(density(Y2_obs_MNAR), lwd = 2, col = "red")

legend(8, 0.25, legend =c("Complete data", "Regression Input","Observed Data"),col =c("blue", "green", "red"), lty =c(1,1,1), lwd =c(2,2,2), bty ="n")


```



Question 4a


```{r}
load("databp.Rdata")

#Code attribution is week2 workshop solutions, url at top

#Create an index of which values are not NAs
ind = which(is.na(databp$recovtime) == FALSE)

#then calculate the mean and standard deviation, na.rm = TRUE discounts any NAs from the calculation
meancomp = mean(databp$recovtime, na.rm = TRUE)
sdcomp = sd(databp$recovtime, na.rm = TRUE)/sqrt(length(comp))



meancomp ; sdcomp



#Calculating the Pearson coeficcient using code from Quick-R by data camp, url at top.

#x= and y= specify our data to compare, use="complete.obs" instructs R to handle missing data using listwise deletion, and method is fairly self explanatory.

reco_dose_cor = cor(x = databp$recovtime, y = databp$logdose, use="complete.obs", method="pearson")

reco_bp_cor = cor(x = databp$recovtime, y = databp$bloodp, use="complete.obs", method="pearson")

reco_dose_cor ; reco_bp_cor
```


Question 4b


```{r}
#Take the mean of recorvery time, discarding NA's
meancomp = mean(databp$recovtime, na.rm = TRUE)

#Write this mean into our data set, replacing NAs

minput = ifelse(is.na(databp$recovtime) == TRUE, meancomp, databp$recovtime)


#Then repeat previous code, use minput as our new data set for recovtime
mean_minput = mean(minput)
sd_minput = sd(minput)/sqrt(length(minput))

mean_minput ; sd_minput

minput_dose_cor = cor(x = minput, y = databp$logdose, method="pearson")

minput_bp_cor = cor(x = minput, y = databp$bloodp, method="pearson")

minput_dose_cor ; minput_bp_cor

```




Question 4c


```{r}

#Use the lm function for recoverytime matched with dose and bp
fitreco = lm(databp$recovtime ~ databp$logdose + databp$bloodp)


#Now calculate the new values for reco time using the linear model. Our missing values are at index 4, 10 and 22.

predreco = predict(fitreco, newdata = databp)



#Now rewrite the NAs in the data using this model
reg_reco = ifelse(is.na(databp$recovtime) == TRUE, predreco, databp$recovtime)

mean_rinput = mean(reg_reco)
sd_rinput = sd(reg_reco)/sqrt(length(reg_reco))

mean_rinput ; sd_rinput

rinput_dose_cor = cor(x = reg_reco, y = databp$logdose, method="pearson")

rinput_bp_cor = cor(x = reg_reco, y = databp$bloodp, method="pearson")

rinput_dose_cor ; minput_bp_cor


```